### ISSUE TITLE
Access Forbidden

### ISSUE THREAD

**Issue by shakdwipeea** [mighdoll/sparkle#4]
Cannot access [Sparkle intro talk](https://docs.google.com/presentation/d/1yBgxGrqJ0TR2VONKN_Lfol49lyUb3CZ-o_JiEclO0aY/pub?start=false&loop=false&delayms=3000#slide=id.p)

**Comment by mighdoll** [comment]
grr, sorry 'bout that.

The pdf is here: https://cdn.parleys.com/p/53a7d2cce4b0543940d9e55a/g3ZWPlN7Oj5-SparkleIntroTalk1.pdf (no animations in the pdf though!)

This more recent set of slides is still accessible: https://docs.google.com/presentation/d/1q3upEFivpx-IClqiDlFHl4FQZrLRWAWdYiFI-keJbQU/edit?usp=sharing

**Comment by shakdwipeea** [comment]
I've requested access for the recent slides. Meanwhile I think this [video](https://www.parleys.com/tutorial/sparkle-reactive-streams-browser-scala-d3) should be added
