### ISSUE TITLE
The link to "Visualize the Things" links to gated content

### ISSUE THREAD

**Issue by lutzh** [mighdoll/sparkle#6]
Due to lack of permission I can't access [Visualize the Things](https://docs.google.com/presentation/d/1q3upEFivpx-IClqiDlFHl4FQZrLRWAWdYiFI-keJbQU/edit#slide=id.g7bf2bd9b8_30), nor [Sparkle Intro Talk](https://docs.google.com/a/nestlabs.com/presentation/d/1yBgxGrqJ0TR2VONKN_Lfol49lyUb3CZ-o_JiEclO0aY/pub?start=false&loop=false&delayms=3000#slide=id.p), which are linked to in the Readme.md.

**Comment by intracer** [comment]
+1, most links are not working

**Comment by mighdoll** [comment]
try it now. (crossing fingers)

**Comment by lutzh** [comment]
Still unaccessible..
