### ISSUE TITLE
Links on Readme.md are broken

### ISSUE THREAD

**Issue by giampaolotrapasso** [mighdoll/sparkle#7]
I would like to read how to build or contribute, but links to that documentation are broken,

**Comment by mighdoll** [comment]
pull master and try it now? Also, note that there is some updated doc in doc/src/jekyll (site's not yet published anywhere, but feel free to take a peek, see https://github.com/mighdoll/sparkle/blob/master/doc/src/jekyll/doc/Building.md)

**Comment by giampaolotrapasso** [comment]
Thanks Lee
